// Generated by CoffeeScript 1.6.3
(function() {
  var module;

  module = angular.module('app', ['classy', 'classy-on']);

  module.classy.controller({
    name: 'MainController',
    inject: ['$scope', '$element', '$attrs', '$rootScope'],
    broadcastMessage: function(message) {
      this.$rootScope.$broadcast('specialEvent', message);
    }
  });

  module.classy.controller({
    name: 'ClassyController',
    inject: ['$scope', '$element', '$attrs'],
    init: function() {
      this.$.message = "None";
    },
    on: {
      specialEvent: function(event, message) {
        this.$.message = message;
      }
    }
  });

}).call(this);
